apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
      - name: app-api
        image: 'us.gcr.io/singular-elixir-308623/api:v1'